name = "competence-site"
compatibility_date = "2026-07-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "competence-db"
database_id = "a23e3497-2f70-48c4-9f95-af493a5e8204"

[[r2_buckets]]
binding = "DOCS"
bucket_name = "competence-documents"
