export type AdminTestimonial = {
  id: number;
  slug: string;
  name: string;
  destination: string;
  text: string;
  photo: string;
  featured: boolean;
  sortOrder: number;
  status: "draft" | "published";
  createdAt: string;
  updatedAt: string;
};

export type AdminCountry = {
  id: number;
  slug: string;
  name: string;
  code: string;
  tagline: string;
  heroGradient: string;
  accent: string;
  photo: string;
  summary: string;
  capital: string;
  language: string;
  currency: string;
  intakeMonths: string;
  visaProcessing: string;
  programLength: string;
  tuitionFrom: string;
  workRights: string;
  featured: boolean;
  highlights: string[];
  programs: { name: string; length: string; note: string; tuition?: string }[];
  visaSteps: { title: string; detail: string }[];
  requirements: string[];
  documents: string[];
  faqs: { q: string; a: string }[];
  specializations: { name: string; photo: string }[];
  status: "draft" | "published";
  createdAt: string;
  updatedAt: string;
};
