export type AdminTestimonial = {
  id: number;
  slug: string;
  name: string;
  destination: string;
  text: string;
  photo: string;
  featured: boolean;
  sortOrder: number;
  status: "draft" | "published";
  createdAt: string;
  updatedAt: string;
};

export type AdminApplication = {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  country: string;
  destination: string;
  program: string;
  message: string;
  status: string;
  createdAt: string;
};

export type AdminApplicationDocument = {
  id: number;
  applicationId: string;
  docType: string;
  filename: string;
  sizeBytes: number | null;
  createdAt: string;
};

export type AdminUniversity = {
  id: number;
  slug: string;
  countrySlug: string;
  name: string;
  city: string;
  tagline: string;
  heroPhoto: string;
  rankingNational: number | null;
  rankingWorld: number | null;
  foundedYear: number | null;
  studentPopulation: number | null;
  internationalStudentPct: number | null;
  campusType: string;
  gallery: string[];
  videoUrl: string;
  accreditations: string[];
  accommodationSummary: string;
  accommodationCostRange: string;
  studentLife: string[];
  faqs: { q: string; a: string }[];
  featured: boolean;
  status: "draft" | "published";
  createdAt: string;
  updatedAt: string;
};

export type AdminProgram = {
  id: number;
  slug: string;
  universitySlug: string;
  name: string;
  overview: string;
  photo: string;
  degreeType: string;
  fieldOfStudy: string;
  durationMonths: number | null;
  tuitionPerYear: number | null;
  applicationFee: number | null;
  deposit: number | null;
  currency: string;
  entryRequirements: string[];
  minGpa: number | null;
  minIelts: number | null;
  minToefl: number | null;
  requiredDocuments: string[];
  modules: { year: number; courses: string[] }[];
  careerProspects: string[];
  scholarships: { name: string; amount?: string; note?: string }[];
  faqs: { q: string; a: string }[];
  status: "draft" | "published";
  createdAt: string;
  updatedAt: string;
};

export type AdminCountry = {
  id: number;
  slug: string;
  name: string;
  code: string;
  tagline: string;
  heroGradient: string;
  accent: string;
  photo: string;
  summary: string;
  capital: string;
  language: string;
  currency: string;
  intakeMonths: string;
  visaProcessing: string;
  programLength: string;
  tuitionFrom: string;
  workRights: string;
  featured: boolean;
  highlights: string[];
  programs: { name: string; length: string; note: string; tuition?: string }[];
  visaSteps: { title: string; detail: string }[];
  requirements: string[];
  documents: string[];
  faqs: { q: string; a: string }[];
  specializations: { name: string; photo: string }[];
  status: "draft" | "published";
  createdAt: string;
  updatedAt: string;
};
